[logger]
messageFormat = "%(asctime)s :: %(levelname)s :: %(module)s :: %(funcName)s :: %(message)s"

[theme]
primaryColor = "#0095d9"
backgroundColor = "#22272e"
secondaryBackgroundColor = "#2d333b"
textColor = "#adbac4"

[server]
# you will need this for local development:
runOnSave = true

# you will need this if running docker on windows host:
# fileWatcherType = "poll"
fileWatcherType = "last-modified"
